ICV_HOME_DIR      = /DCNFS/applications/synopsys/2019/app/icvalidator/Q-2019.12-SP1-1
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = lab2
INLIB_PATH        = 
BLOCK             = inverter
PYDB_PATH         = run_details/pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.drc.9m_saed90_icv.drc.rs
