#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/fulladd.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/run_details/duse_master.tmp && \
mv /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/run_details/duse_master.tmp /DCNFS/users/student/mpang/ELEN153/Adder/synopsys_custom/pvjob_Fourbit.fulladd.icv.lvs/run_details/duse_master
