#! /bin/sh

echo $HOSTNAME | grep linux400512.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 22254 
else 
rsh linux400512.dc.engr.scu.edu kill 22254 
 sleep 10 
rsh linux400512.dc.engr.scu.edu kill -9 22254 
fi
