ICV_HOME_DIR      = /DCNFS/applications/synopsys/2019/app/icvalidator/Q-2019.12-SP1-1
ICV_COORDS_BIT    = 32
WORKING_DIR       = .
INLIB             = lab4
INLIB_PATH        = 
BLOCK             = NMOS
PYDB_PATH         = TOPCELLNAME_err
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
REPORT_LAYOUT_ERRORS = HIERARCHICAL
FORMAT            = OPENACCESS
SCHEMATIC         = NMOS.sch_out
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.lvs.9m_saed90_lvs.lvs.rs
ENVIRONMENT STRING  SAED90_PDK = "/opt/synopsys-2019/app/SAED/SAED_PDK90nm"
EXTRACTION_FLOW   = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
WRITE_EQUIV_NETLISTS = ALL
