#! /bin/sh

echo $HOSTNAME | grep linux400512.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 7449 
else 
rsh linux400512.dc.engr.scu.edu kill 7449 
 sleep 10 
rsh linux400512.dc.engr.scu.edu kill -9 7449 
fi
