#! /bin/sh

echo $HOSTNAME | grep linux400512.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 25297 
else 
rsh linux400512.dc.engr.scu.edu kill 25297 
 sleep 10 
rsh linux400512.dc.engr.scu.edu kill -9 25297 
fi
