all: Lab2a.c Lab2b.c Lab2c.c Lab2d.c Lab2e.c Lab2f.c
	gcc -o 1 Lab2a.c
	gcc -o 3 Lab2b.c
	gcc -o 5 Lab2c.c 
	gcc -o 6 Lab2d.c
	gcc -lpthread -o 8 Lab2e.c
	gcc -o 7 Lab2f.c 

clean:; rm -f 1 3 5 6 7 8
