#! /bin/sh

echo $HOSTNAME | grep linux400512.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 17487 
else 
rsh linux400512.dc.engr.scu.edu kill 17487 
 sleep 10 
rsh linux400512.dc.engr.scu.edu kill -9 17487 
fi
