#! /bin/sh

echo $HOSTNAME | grep linux400512.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 21947 
else 
rsh linux400512.dc.engr.scu.edu kill 21947 
 sleep 10 
rsh linux400512.dc.engr.scu.edu kill -9 21947 
fi
